services:
  - type: web
    name: candoo-clarity
    runtime: python
    repo: https://github.com/jamescandoo/candoo-clarity
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
